using System.Text.Json;
using HospitalManagementSystem.Api.Data;
using HospitalManagementSystem.Api.DTOs;
using HospitalManagementSystem.Api.Models;
using Microsoft.EntityFrameworkCore;

namespace HospitalManagementSystem.Api.Services;

/// <summary>
/// Safety-first prototype workflow. Clinical rules are configured, versioned and deterministic;
/// no LLM is trusted to make a clinical decision or execute an action.
/// </summary>
public sealed class TriageWorkflowService : ITriageWorkflowService
{
    private const string RuleSetVersion = "safetriage-rules-v1";
    private readonly ApplicationDbContext _db;
    private readonly ILogger<TriageWorkflowService> _logger;

    // These reviewable phrases are deliberately configuration-like safety triggers, not diagnostic thresholds.
    private static readonly string[] EmergencyPhrases =
    [
        "severe chest pain", "difficulty breathing", "cannot breathe", "loss of consciousness",
        "unconscious", "signs of stroke", "face drooping", "severe bleeding", "seizure",
        "severe allergic reaction", "severe confusion"
    ];

    public TriageWorkflowService(ApplicationDbContext db, ILogger<TriageWorkflowService> logger)
    {
        _db = db;
        _logger = logger;
    }

    public async Task<TriageWorkflowDto> StartForPatientAsync(int patientId, StartTriageWorkflowDto request)
    {
        var workflow = new TriageWorkflow
        {
            PatientId = patientId,
            Symptoms = request.Symptoms.Trim(),
            VitalsJson = request.Vitals is null ? null : JsonSerializer.Serialize(request.Vitals),
            PlanJson = JsonSerializer.Serialize(CreatePlan()),
            RuleSetVersion = RuleSetVersion,
        };
        _db.TriageWorkflows.Add(workflow);
        await AddEvent(workflow, "IntakeValidationAgent", "Started", new { source = "patient-reported" });

        var validationProblems = Validate(request);
        var redFlags = FindRedFlags(request.Symptoms);
        var riskFactors = new List<string>();
        var missingInformation = new List<string>();

        if (request.Vitals is null) missingInformation.Add("No verified vital signs were supplied.");
        if (validationProblems.Count > 0)
        {
            workflow.Status = TriageWorkflowStatuses.FailedSafely;
            workflow.TriageLevel = TriageLevels.InsufficientInformation;
            workflow.UncertaintyState = TriageUncertaintyStates.LimitedInformation;
            workflow.RequiresHumanReview = true;
            workflow.ErrorCode = "InvalidOrSuspiciousInput";
            workflow.FinalOutcome = "The system cannot safely assess this situation with the available information. Please seek assessment from a qualified healthcare professional.";
            missingInformation.AddRange(validationProblems);
            await AddEvent(workflow, "IntakeValidationAgent", "FailedSafely", new { validationProblems });
        }
        else if (redFlags.Count > 0)
        {
            workflow.Status = TriageWorkflowStatuses.PendingClinicalReview;
            workflow.ApprovalStatus = TriageApprovalStatuses.Pending;
            workflow.TriageLevel = TriageLevels.Emergency;
            workflow.UncertaintyState = TriageUncertaintyStates.HumanReviewRequired;
            workflow.RequiresHumanReview = true;
            riskFactors.Add("Configured emergency red-flag phrase detected in patient-reported symptoms.");
            workflow.FinalOutcome = "Emergency escalation was triggered because submitted symptoms matched configured emergency criteria. Seek immediate emergency evaluation; this decision-support result is not a diagnosis.";
            await AddEvent(workflow, "SafetyRedFlagAgent", "EmergencyEscalation", new { redFlags, ruleSetVersion = RuleSetVersion });
            await AddEvent(workflow, "CareRoutingAgent", "Proposed", new { route = "Emergency Department", requiresClinicalApproval = true });
        }
        else
        {
            // Conservative, non-diagnostic routing. A future evidence-grounded model can only propose within this schema.
            workflow.Status = TriageWorkflowStatuses.Completed;
            workflow.TriageLevel = TriageLevels.InsufficientInformation;
            workflow.UncertaintyState = TriageUncertaintyStates.LimitedInformation;
            workflow.RequiresHumanReview = true;
            workflow.FinalOutcome = "No configured emergency red flag was detected. This system cannot determine a diagnosis or clinical urgency from symptoms alone. Please obtain assessment from a qualified healthcare professional.";
            missingInformation.Add("Clinical assessment is required; no diagnosis is generated by this workflow.");
            await AddEvent(workflow, "ClinicalInformationExtractionAgent", "Structured", new { patientReportedSymptoms = true });
            await AddEvent(workflow, "RiskAssessmentAgent", "ConservativeFallback", new { triageLevel = workflow.TriageLevel });
            await AddEvent(workflow, "SafetyValidationAgent", "Accepted", new { requiresHumanReview = true });
        }

        workflow.ResultJson = JsonSerializer.Serialize(new { riskFactors, redFlags, missingInformation, workflow.FinalOutcome });
        workflow.UpdatedAt = DateTime.UtcNow;
        await _db.SaveChangesAsync();
        _logger.LogInformation("SafeTriage workflow {WorkflowId} created for patient {PatientId} with status {Status}", workflow.TriageWorkflowId, patientId, workflow.Status);
        return Map(workflow, riskFactors, redFlags, missingInformation);
    }

    public async Task<TriageWorkflowDto?> GetForPatientAsync(int workflowId, int patientId)
    {
        var workflow = await _db.TriageWorkflows.AsNoTracking().SingleOrDefaultAsync(x => x.TriageWorkflowId == workflowId && x.PatientId == patientId);
        return workflow is null ? null : Map(workflow);
    }

    public async Task<TriageWorkflowDto?> GetForClinicalReviewerAsync(int workflowId)
    {
        var workflow = await _db.TriageWorkflows.AsNoTracking().SingleOrDefaultAsync(x => x.TriageWorkflowId == workflowId);
        return workflow is null ? null : Map(workflow);
    }

    public async Task<IReadOnlyList<TriageWorkflowDto>> GetPendingClinicalReviewsAsync()
    {
        var workflows = await _db.TriageWorkflows.AsNoTracking()
            .Where(x => x.ApprovalStatus == TriageApprovalStatuses.Pending)
            .OrderBy(x => x.CreatedAt)
            .ToListAsync();
        return workflows.Select(workflow => Map(workflow)).ToList();
    }

    public async Task<IReadOnlyList<TriageWorkflowEventDto>?> GetAuditEventsAsync(int workflowId)
    {
        var exists = await _db.TriageWorkflows.AsNoTracking().AnyAsync(x => x.TriageWorkflowId == workflowId);
        if (!exists) return null;
        return await _db.TriageWorkflowEvents.AsNoTracking()
            .Where(x => x.TriageWorkflowId == workflowId)
            .OrderBy(x => x.CreatedAt)
            .Select(x => new TriageWorkflowEventDto { Stage = x.Stage, EventType = x.EventType, CreatedAt = x.CreatedAt })
            .ToListAsync();
    }

    public async Task<TriageWorkflowDto?> ReviewAsync(int workflowId, int reviewerUserId, ReviewTriageWorkflowDto request)
    {
        var workflow = await _db.TriageWorkflows.SingleOrDefaultAsync(x => x.TriageWorkflowId == workflowId);
        if (workflow is null || workflow.ApprovalStatus != TriageApprovalStatuses.Pending) return null;

        var decision = request.Decision.Trim();
        if (decision is not (TriageApprovalStatuses.Approved or TriageApprovalStatuses.Rejected or TriageApprovalStatuses.RevisionRequested))
            throw new ArgumentException("Decision must be Approved, Rejected, or RevisionRequested.");

        workflow.ApprovalStatus = decision;
        workflow.ReviewedByUserId = reviewerUserId;
        workflow.ReviewedAt = DateTime.UtcNow;
        workflow.UpdatedAt = DateTime.UtcNow;
        workflow.Status = decision == TriageApprovalStatuses.RevisionRequested ? TriageWorkflowStatuses.PendingClinicalReview : TriageWorkflowStatuses.Completed;
        workflow.FinalOutcome = decision switch
        {
            TriageApprovalStatuses.Approved => "A clinical reviewer approved the emergency escalation recommendation.",
            TriageApprovalStatuses.Rejected => "A clinical reviewer did not approve the proposed escalation. Contact the care team for further guidance.",
            _ => "A clinical reviewer requested additional information before a decision can be made."
        };
        await AddEvent(workflow, "HumanClinicalReview", decision, new { note = request.Note?.Trim(), reviewerUserId });
        await _db.SaveChangesAsync();
        return Map(workflow);
    }

    private async Task AddEvent(TriageWorkflow workflow, string stage, string eventType, object details)
        => await _db.TriageWorkflowEvents.AddAsync(new TriageWorkflowEvent { TriageWorkflow = workflow, Stage = stage, EventType = eventType, DetailsJson = JsonSerializer.Serialize(details) });

    private static List<string> Validate(StartTriageWorkflowDto request)
    {
        var errors = new List<string>();
        var vitals = request.Vitals;
        if (vitals is null) return errors;
        if (vitals.TemperatureCelsius is < 25 or > 45) errors.Add("Temperature is outside the accepted input range.");
        if (vitals.HeartRateBpm is < 20 or > 300) errors.Add("Heart rate is outside the accepted input range.");
        if (vitals.SystolicBloodPressure is < 40 or > 300 || vitals.DiastolicBloodPressure is < 20 or > 200) errors.Add("Blood pressure is outside the accepted input range.");
        if (vitals.SystolicBloodPressure.HasValue && vitals.DiastolicBloodPressure.HasValue && vitals.SystolicBloodPressure <= vitals.DiastolicBloodPressure) errors.Add("Blood pressure values are contradictory.");
        if (vitals.OxygenSaturationPercent is < 1 or > 100) errors.Add("Oxygen saturation must be between 1 and 100 percent.");
        if (vitals.ObservedAt > DateTime.UtcNow.AddMinutes(5)) errors.Add("Vital-sign observation time cannot be in the future.");
        return errors;
    }

    private static List<string> FindRedFlags(string symptoms) => EmergencyPhrases.Where(phrase => symptoms.Contains(phrase, StringComparison.OrdinalIgnoreCase)).ToList();
    private static IReadOnlyList<TriagePlanStepDto> CreatePlan() =>
    [
        new() { Agent = "IntakeValidationAgent", Status = "Planned", Purpose = "Validate patient-reported inputs and vital-sign integrity." },
        new() { Agent = "ClinicalInformationExtractionAgent", Status = "Planned", Purpose = "Structure patient-reported information without inventing facts." },
        new() { Agent = "SafetyRedFlagAgent", Status = "Planned", Purpose = "Apply versioned deterministic emergency rules." },
        new() { Agent = "RiskAssessmentAgent", Status = "Planned", Purpose = "Propose only controlled triage categories." },
        new() { Agent = "CareRoutingAgent", Status = "Planned", Purpose = "Propose an approved care path; never book or prescribe." },
        new() { Agent = "SafetyValidationAgent", Status = "Planned", Purpose = "Validate output and enforce escalation/approval rules." },
    ];

    private static TriageWorkflowDto Map(TriageWorkflow workflow, List<string>? risks = null, List<string>? flags = null, List<string>? missing = null)
    {
        if (risks is null || flags is null || missing is null)
        {
            using var result = JsonDocument.Parse(workflow.ResultJson);
            risks = result.RootElement.TryGetProperty("riskFactors", out var riskElement) ? riskElement.Deserialize<List<string>>() ?? [] : [];
            flags = result.RootElement.TryGetProperty("redFlags", out var flagElement) ? flagElement.Deserialize<List<string>>() ?? [] : [];
            missing = result.RootElement.TryGetProperty("missingInformation", out var missingElement) ? missingElement.Deserialize<List<string>>() ?? [] : [];
        }
        return new TriageWorkflowDto { WorkflowId = workflow.TriageWorkflowId, Status = workflow.Status, ApprovalStatus = workflow.ApprovalStatus, TriageLevel = workflow.TriageLevel, UncertaintyState = workflow.UncertaintyState, RequiresHumanReview = workflow.RequiresHumanReview, PatientMessage = workflow.FinalOutcome ?? "The system cannot safely assess this situation.", RiskFactors = risks, RedFlags = flags, MissingInformation = missing, Plan = JsonSerializer.Deserialize<List<TriagePlanStepDto>>(workflow.PlanJson) ?? [], RuleSetVersion = workflow.RuleSetVersion, CreatedAt = workflow.CreatedAt };
    }
}
